---
# tasks file for squid
- name: include assert.yml
  include_tasks: assert.yml

- name: install squid
  package:
    name: "{{ squid_packages }}"
    state: present

- name: configure squid
  template:
    src: "{{ squid_config_file }}.j2"
    dest: "{{ squid_config_directory }}/{{ squid_config_file }}"
    mode: "0644"
  notify:
    - test squid configuration
    - restart squid

- name: copy url allow / block list
  copy:
    src: "{{ item }}"
    dest: "{{ squid_config_directory }}/"
    mode: "0644"
  loop:
    - "{{ squid_allowlist | default([]) }}"
    - "{{ squid_denylist | default([]) }}"
  notify:
    - test squid configuration
    - restart squid

- name: create group
  group:
    name: "{{ squid_group }}"
    system: yes
    state: present

- name: create user
  user:
    name: "{{ squid_user }}"
    group: "{{ squid_group }}"
    create_home: no
    state: present
    home: /var/spool/squid
    shell: /sbin/nologin
    system: yes

- name: create cache directory
  file:
    path: /var/spool/squid
    state: directory
    owner: "{{ squid_user }}"
    group: "{{ squid_group }}"
    mode: "0750"

- name: flush_handlers
  meta: flush_handlers

- name: start and enable squid
  service:
    name: "{{ squid_service }}"
    state: started
    enabled: yes
